name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (use npm)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Ensure clean state (remove yarn leftovers)
        run: |
          rm -f yarn.lock
          rm -rf node_modules

      - name: Install dependencies (npm)
        run: npm ci

      - name: Ensure NuxtHub module is installed
        # If npx nuxthub... previously caused rollup/native errors,
        # try running it after a clean npm ci. If this step fails,
        # consider adding @nuxthub/core to package.json devDependencies instead.
        run: npx nuxthub@latest ensure

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: kimyonazarov-6a35
