- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: 18
    cache: 'npm'

- name: Ensure clean state
  run: |
    rm -f yarn.lock
    rm -rf node_modules
    npm cache clean --force

- name: Install OS build tools (for native modules)
  run: |
    sudo apt-get update
    sudo apt-get install -y build-essential python3 make g++

- name: Install dependencies (npm)
  run: npm ci

- name: Try rebuild native modules if binding missing
  # try to build from source if optional native binaries were not installed
  run: |
    node -e "try { require('oxc-parser'); console.log('oxc-parser ok'); } catch(e) { console.log('oxc-parser missing - rebuilding'); process.exit(1); }" || npm rebuild --build-from-source
